enum ActinTypes {
  RECEIVE_CITY_LIST = 'RECEIVE_CITY_LIST',
  PUSH_ROUTER = 'PUSH_ROUTER',
  FETCH_FOO = 'FETCH_FOO',
  RECEIVE_FOO = 'RECEIVE_FOO',
  REMOVE_TAB_PAGE = 'REMOVE_TAB_PAGE',
  ADD_TAB_PAGE = 'ADD_TAB_PAGE',
  CHANGE_CURRENT_TAB_PAGE = 'CHANGE_CURRENT_TAB_PAGE',
  REMOVE_ALL_TAB_PAGE = 'REMOVE_ALL_TAB_PAGE',

  GET_FORM_DATA = 'GET_FORM_DATA',
  RECEIVE_FORM_DATA = 'RECEIVE_FORM_DATA',
  SAVE_FORM_DATA = 'SAVE_FORM_DATA',
}
export default ActinTypes;

export enum LocationChangeType {
  LOCATION_CHANGE = `@@router/LOCATION_CHANGE`,
}
